AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate Stack

Resources:
  AppCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: spring-service-cluster

  AppECRRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: spring-service

  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

Outputs:
  ClusterName:
    Value: !Ref AppCluster
  ECRRepoURI:
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${AppECRRepo}